apiVersion: v1
kind: Service
metadata:
  name: argocd-helm-nginx
  labels:
    app: argocd-helm-nginx
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
  selector:
    app: argocd-helm-nginx
    release: {{ .Release.Name }}